# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-12 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name=b'Nome do Fornecedor')),
                ('phone', models.CharField(max_length=30, verbose_name=b'Telefone')),
                ('phone2', models.CharField(blank=True, max_length=30, null=True, verbose_name=b'Telefone 2')),
                ('city', models.CharField(max_length=30, verbose_name=b'Cidade')),
                ('state', models.CharField(max_length=255, verbose_name=b'Estado')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=b'providers/', verbose_name=b'Foto do fornecedor')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=b'providers/logos/', verbose_name=b'Logo do fornecedor')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name=b'Email')),
                ('site', models.URLField(blank=True, max_length=255, null=True, verbose_name=b'Site')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True, verbose_name=b'Facebook')),
                ('instagram', models.URLField(blank=True, max_length=255, null=True, verbose_name=b'Instagram')),
                ('pinterest', models.URLField(blank=True, max_length=255, null=True, verbose_name=b'Pinterest')),
                ('gogudi', models.URLField(blank=True, max_length=255, null=True, verbose_name=b'Gogudi')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name=b'P\xc3\xa1gina Interna')),
                ('content', models.TextField(blank=True, null=True, verbose_name=b'Conteudo')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Contato ',
                'verbose_name_plural': 'Contato',
            },
        ),
    ]
