# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-12 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='gogudi',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='pinterest',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='slug',
        ),
    ]
