# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-12 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=b'content/', verbose_name=b'Foto do conteudo')),
                ('text', models.CharField(max_length=255, verbose_name=b'Texto')),
                ('subtitle', models.CharField(max_length=255, verbose_name=b'Legenda')),
            ],
            options={
                'verbose_name': 'Conte\xfado',
                'verbose_name_plural': 'Conte\xfado',
            },
        ),
    ]
